- id: nocommit-comment
  name: Prevent commiting files with NOCOMMIT comments
  description: Any file containing 'NOCOMMIT' (case insensitive) cannot be committed
  language: pygrep
  types: [text]
  args: [-i] # case insensitive
  entry: 'NOCOMMIT'
  exclude: >
            (?x)^(
                .pre-commit-.+|
                path/to/file2.py|
                path/to/file3.py
            )$